name: CronJob
on:
  schedule:
    - cron: "0 23 * * *" # everyday at 11pm UTC
  push:
jobs:
  runCLI:
    name: DrawCalculator CLI
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node: ["16.9.0"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      - name: Run Draw Calculator CLI (if required)
        uses: maddog2050/executable-wrapper@v1
        id: runDrawCalculatorCLI
        continue-on-error: true
        env:
          ALCHEMY_MAINNET_URL: ${{secrets.ALCHEMY_MAINNET_URL}}
          ALCHEMY_RINKEBY_URL: ${{secrets.ALCHEMY_RINKEBY_URL}}
          MATICVIGIL_URL: ${{secrets.MATICVIGIL_URL}}
          AVALANCHE_URL: ${{secrets.AVALANCHE_URL}}
          MUMBAI_URL: ${{secrets.MUMBAI_URL}}
          DEBUG: ${{secrets.DEBUG}}
        with:
          run_command: node ./scripts/runCli.js
      - name: Comment Error
        id: commentCalculatorError
        uses: actions/github-script@v5
        continue-on-error: true
        if: steps.runDrawCalculatorCLI.outputs.exitcode == 9
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: 11,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Draw Calculator failed on an unexpected error'
            })
      - name: Retry Draw Calculator
        uses: nick-invision/retry@v2
        if: steps.runDrawCalculatorCLI.outputs.exitcode == 2
        id: retryDrawCalculatorCLI
        with:
          timeout_seconds: 2500000 # 25 minutes
          max_attempts: 2
          retry_on: error
          command: node ./scripts/runCli.js
      - name: Commit files for polygon (if required)
        if: steps.runDrawCalculatorCLI.outputs.polygonCliToolRan == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git add ./api/prizes/137/
          git commit -m "Add draw for polygon draw ${{steps.runDrawCalculatorCLI.outputs.polygonDrawId}}"

      - name: Commit files for mainnet (if required) # this is done seperately to polygon for a different commit message
        if: steps.runDrawCalculatorCLI.outputs.mainnetCliToolRan == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git add ./api/prizes/1/
          git commit -m "Add draw for mainnet draw ${{steps.runDrawCalculatorCLI.outputs.mainnetDrawId}}"

      - name: Commit files for avalanche (if required) # this is done seperately to polygon for a different commit message
        if: steps.runDrawCalculatorCLI.outputs.avalancheCliToolRan == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git add ./api/prizes/43114/
          git commit -m "Add draw for avalanche draw ${{steps.runDrawCalculatorCLI.outputs.avalancheDrawId}}"

      - name: Push changes (if required)
        uses: ad-m/github-push-action@master
        if: steps.runDrawCalculatorCLI.outputs.polygonCliToolRan == 'true' || steps.runDrawCalculatorCLI.outputs.mainnetCliToolRan == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
